---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "dotnet-sdk"
    directory: "/src"
    schedule:
      interval: "weekly"
