# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main
  
# no PR triggers
pr: none

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: Tests
    inputs:
      command: 'test'
      projects: |
        tests/Sushi.MediaKiwi.DAL.UnitTests/*.csproj
        tests/Sushi.MediaKiwi.Services.UnitTests/*.csproj
  - task: DotNetCoreCLI@2
    displayName: Build Sample API
    inputs:
      command: "publish"
      publishWebProjects: false
      arguments: "src/Sushi.MediaKiwi.SampleAPI/Sushi.MediaKiwi.SampleAPI.csproj --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: true
  - task: PublishBuildArtifacts@1
    displayName: Publish artifacts
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"