# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

# no PR triggers
pr: none

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: "Release"

steps:
  # Install Dependencies
  - task: NodeTool@0
    displayName: "Install Node"
    inputs:
      versionSource: "spec"
      versionSpec: "18.x"
      checkLatest: true

  - task: Npm@1
    displayName: "Npm install on MediaKiwi.Vue"
    inputs:
      command: "ci"
      workingDir: "src/Sushi.MediaKiwi.Vue"

  # Build and Pack mediakiwi-vue
  - task: Npm@1
    displayName: "Npm build on MediaKiwi.Vue"
    inputs:
      command: "custom"
      workingDir: "src/Sushi.MediaKiwi.Vue"
      customCommand: "run build:prd"

  - task: Npm@1
    displayName: "Npm pack on MediaKiwi.Vue"
    inputs:
      command: "custom"
      workingDir: "src/Sushi.MediaKiwi.Vue"
      customCommand: "pack --pack-destination=package"
  
  - task: CopyFiles@2
    inputs:
      SourceFolder: "package"
      Contents: '*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'