# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: "publish"
      publishWebProjects: false
      arguments: "src/Sushi.MediaKiwi.SampleAPI/Sushi.MediaKiwi.SampleAPI.csproj --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: true

  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '18.x'
      checkLatest: true

  - task: Npm@1
    inputs:
      command: 'ci'
      workingDir: 'src/Sushi.MediaKiwi.SampleWeb/ClientApp'
    displayName: "npm install on SampleWeb"

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'src/Sushi.MediaKiwi.SampleWeb/ClientApp'
      customCommand: 'run build'
    displayName: "npm build on SampleWeb"

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'src/Sushi.MediaKiwi.SampleWeb'
      Contents: |
        ClientApp/dist/**
        Function/**
      TargetFolder: 'SampleWeb'
    displayName: "Copy ClientApp/dist and Function to SampleWeb"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
  
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'SampleWeb'
      artifact: 'drop'
      publishLocation: 'pipeline' 