/** Icons and aliasses being used in Mediakiwi based on Material Design Icons*/
export enum IconsLibrary {
  // default icon aliases (from vuetify)
  collapse = "$chevronUp",
  complete = "$check",
  cancel = "$cancel",
  close = "$close",
  delete = "$delete",
  clear = "$closeCircleOutline",
  success = "$checkCircleOutline",
  info = "$informationOutline",
  warning = "$alertOctagonOutline",
  error = "$alertCircle",
  prev = "$chevronLeft",
  next = "$chevronRight",
  checkboxOn = "$checkboxOutline",
  checkboxOff = "$checkboxBlankOutline",
  checkboxIndeterminate = "$minusBoxOutline",
  delimiter = "$dotsVertical",
  sort = "$sort",
  expand = "$chevronDown",
  menu = "$menu",
  subgroup = "$subdirectoryArrowRight",
  dropdown = "$chevronDown",
  radioOn = "$radioboxMarked",
  radioOff = "$radioboxBlank",
  edit = "$pencil",
  ratingEmpty = "$starOutline",
  ratingFull = "$star",
  ratingHalf = "$starHalfFull",
  loading = "$loading",
  first = "$pageFirst",
  last = "$pageLast",
  unfold = "$unfoldMoreHorizontal",
  closeCircleOutline = "$closeCircleOutline",
  file = "$file",
  plus = "$plus",
  minus = "$minus",
  sortDesc = "$sortDescending",
  sortAsc = "$sortAscending",
  chevronLeft = "$chevronLeft",
  chevronRight = "$chevronRight",
  informationOutline = "$informationOutline",

  // Mediakiwi: Defaults (some might already be included in the above list)
  unknown = "$checkboxBlankOutline", // used for blank icon placeholder
  arrowLeft = "$arrowLeft",
  arrowRight = "$arrowRight",
  circle = "$circle",
  triangle = "$triangle",
  square = "$square",
  pentagon = "$pentagon",
  hexagon = "$hexagon",
  circleOutline = "$circleOutline",
  triangleOutline = "$triangleOutline",
  squareOutline = "$squareOutline",
  pentagonOutline = "$pentagonOutline",
  hexagonOutline = "$hexagonOutline",
  rewindOutline = "$rewindOutline",
  fastForwardOutline = "$fastForwardOutline",
  playOutline = "$playOutline",
  skipPreviousOutline = "$skipPreviousOutline",
  skipNextOutline = "$skipNextOutline",
  // Some outline icons are part of material design outline and not icons
  bus = "$bus", // bus outline is part of material symbols andn not icons
  trian = "$train", // train outline is part of material symbols andn not icons
  car = "$car", // car outline is part of material symbols andn not icons
  taxi = "$taxi", // taxi outline is part of material symbols andn not icons
  fileGifBox = "$fileGifBox",
  // checkSmall is part of material symbols andn not icons
  // mobileFirendly is part of material symbols andn not icons
  magnify = "$magnify",
  checkboxMarked = "$checkboxMarked",
  minusBox = "$minusBox",
  emailOutline = "$emailOutline",
  bookmark = "$bookmark",
  bookmarkOutline = "$bookmarkOutline",
  accountOutline = "$accountOutline",
  message = "$message",
  messageOutline = "$messageOutline",
  trashCanOutline = "$trashCanOutline",
  folderOutline = "$folderOutline",
  menuDown = "$menuDown",
  menuUp = "$menuUp",
  menuLeft = "$menuLeft",
  menuRight = "$menuRight",
  paperclip = "$paperclip",
  calendarToday = "$calendarToday",
  shareVariantOutline = "$shareVariantOutline",
  keyboardOutline = "$keyboardOutline",
  cogOutline = "$cogOutline",
  cog = "$cog",
  clockOutline = "$clockOutline",
  keyboardReturn = "$keyboardReturn",
  stickerEmoji = "$stickerEmoji",
  dotsHorizontal = "$dotsHorizontal",
  microphone = "$microphone",
  web = "$web",
  googleTranslate = "$googleTranslate",
  imageOutline = "$imageOutline",
  trayArrowUp = "$trayArrowUp",
  trayArrowDown = "$trayArrowDown",

  // ToolBar
  weatherSunny = "$weatherSunny",
  weatherNight = "$weatherNight",
  accountCircle = "$accountCircle",

  // Table
  checkCircleOutline = "$checkCircleOutline",
  dotsVertical = "$dotsVertical",
  arrowUp = "$arrowUp",
  arrowDown = "$arrowDown",
  filterVariant = "$filterVariant",

  // SignIn
  microsoftAzure = "$microsoftAzure",

  // Sections
  home = "$home",
  security = "$security",
}
