// Enums to be used in MKVue project
export enum IconsLibrary {
  // Standard = In Use
  mdiChevronLeft = "$chevronLeft",
  mdiChevronRight = "$chevornRight",
  mdiPuzzle = "$puzzle",

  // Sections
  mdiHome = "$home",
  mdiSecurity = "$security",

  // ToolBar
  mdiWeatherSunny = "$weatherSunny",
  mdiWeatherNight = "$weatherNight",
  mdiAccountCircle = "$accountCircle",

  // Table
  mdiCheckCircleOutline = "$checkCircleOutline",
  mdiDotsVertical = "$dotsVertical",
  mdiCloseCircleOutline = "$ closeCircleOutline",
  mdiArrowUp = "$arrowUp",
  mdiArrowDown = "$arrowDown",
  mdiFilterVariant = "$filterVariant",
  mdiClose = "$close",
  mdiPlus = "$plus",

  // SignIn
  mdiMicrosoftAzure = "$microsoftAzure",

  // Alerts
  mdiInformationOutline = "$informationOutline",

  // Standard = NOT In Use
  midForward = "$forward",
  mdiMinus = "$minus",
  mdiChevronUp = "$chevronUp",
  mdiChevronDown = "$chevronDown",
  mdiPin = "$pin",
  mdiMapMarkerRadius = "$mapMarkerRadius",
  mdiMapSearch = "$mapSearch",
  mdiMagnify = "$magnify",
  mdiMagnifyPlus = "$magnifyPlus",
  mdiMagnifyMinus = "$magnifyMinus",
  mdiUpload = "$upload",
  mdiDownload = "$download",
  mdiAccountGroup = "$accountGroup",
  mdiFolder = "$folder",
  mdiAirplaneLanding = "$airplaneLanding",
  mdiAirplaneTakeoff = "$airplaneTakeoff",
  mdiSend = "$send",
  mdiInbox = "$inbox",
  mdiInboxArrowUp = "$outbox",
  mdiBus = "$bus",
  mdiCar = "$car",
  mdiCogOutline = "$cogOutline",
  mdiClock = "$clock",
  mdiMap = "$map",
  mdiSlashForward = "$slashForward",
  mdiFinance = "$finance",
  mdiViewDashboard = "$viewDashboard",
  mdiCashMultiple = "$cashMultiple",
  mdiBitcoin = "$bitcoin",
  mdiBookmark = "$bookmark",
  mdiStar = "$star",
  mdiBook = "$book",
  mdiArchive = "$archive",
  mdiBug = "$bug",
  mdiFormatListBulletedSquare = "$formatListBulletedSquare",
  mdiPencil = "$pencil",
  mdiChat = "$chat",
  mdiLoginVariant = "$login",
  mdiLogoutVariant = "$logout",
  mdiPhone = "$phone",
  mdiAlertOutline = "$alertOutline",
  mdiAlert = "$alert",
  mdiInformation = "$information",
  mdiHelp = "$help",
  mdiCloudOutline = "$cloudOutline",
  mdiFileDocumentOutline = "$fileDocumentOutline",
  mdiBed = "$bed",
  mdiUmbrella = "$umbrella",
  mdiWaves = "$waves",
  mdiWater = "$water",
  mdiTimerSand = "$timerSand",
  mdiWeb = "$web",
  mdiEarth = "$earth",
  mdiWeatherSnowy = "$weatherSnowy",
  mdiWeatherPouring = "$weatherPouring",
  mdiWeatherWindy = "$weatherWindy",
  mdiWeatherSunset = "$weatherSunset",
  mdiClockOutline = "$clockOutline",
  mdiCalendarMonth = "$calendarMonth",
  mdiCalendarBlank = "$calendarBlank",
  mdiUpdate = "$update",
  mdiLockOutline = "$lockOutline",
  mdiLockOpenOutline = "$lockOpenOutline",
  mdiEyeOutline = "$eyeOutline",
  mdiEyeOffOutline = "$eyeOffOutline",
  mdiHeart = "$heart",
  mdiVolumeOff = "$volumeOff",
  mdiVolumeHigh = "$volumeHigh",
  mdiBlockHelper = "$blockHelper",
  mdiFlagVariant = "$flagVariant",
  mdiSale = "$sale",
  mdiCookieOutline = "$cookieOutline",
  mdiLeaf = "$leaf",
  mdiAlertOctagon = "$alertOctagon",
  mdiMonitor = "$monitor",
  mdiTools = "$tools",
  mdiBankOutline = "$bankOutline",
  mdiEmoticonHappyOutline = "$emoticonHappyOutline",
  mdiEmoticonSadOutline = "$emoticonSadOutline",
  mdiEmoticonSickOutline = "$emoticonSickOutline",
  mdiRobotConfusedOutline = "$robotConfusedOutline",
  mdiRobotHappy = "$robotHappy",
  mdiTranslate = "$translate",
  mdiHandshakeOutline = "$handshakeOutline",
  mdiDumbbell = "$dumbbell",
  mdiEmail = "$email",
  mdiAt = "$at",
  mdiTrashCanOutline = "$trashCanOutline",
  mdiCloseOctagon = "$closeOctagon",
  mdiOpenInNew = "$openInNew",
}
