/** Icons and aliasses being used in Mediakiwi based on Material Design Icons*/
export enum IconsLibrary {
  // default icon aliases (from vuetify)
  collapse = "$chevronUp",
  complete = "$check",
  cancel = "$cancel",
  close = "$close",
  delete = "$delete",
  clear = "$closeCircleOutline",
  success = "$checkCircleOutline",
  info = "$informationOutline",
  warning = "$alertOctagonOutline",
  error = "$alertCircle",
  prev = "$chevronLeft",
  next = "$chevronRight",
  checkboxOn = "$checkboxOutline",
  checkboxOff = "$checkboxBlankOutline",
  checkboxIndeterminate = "$minusBoxOutline",
  delimiter = "$dotsVertical",
  sort = "$sort",
  expand = "$chevronDown",
  menu = "$menu",
  subgroup = "$subdirectoryArrowRight",
  dropdown = "$chevronDown",
  radioOn = "$radioboxMarked",
  radioOff = "$radioboxBlank",
  edit = "$pencil",
  ratingEmpty = "$starOutline",
  ratingFull = "$star",
  ratingHalf = "$starHalfFull",
  loading = "$loading",
  first = "$pageFirst",
  last = "$pageLast",
  unfold = "$unfoldMoreHorizontal",
  closeCircleOutline = "$closeCircleOutline",
  file = "$file",
  plus = "$plus",
  minus = "$minus",
  sortDesc = "$sortDescending",
  sortAsc = "$sortAscending",
  chevronLeft = "$chevronLeft",
  chevronRight = "$chevronRight",
  informationOutline = "$informationOutline",

  // Mediakiwi = Defaults (some might already be included in the above list)
  unknown = "$checkboxBlankOutline", // used for blank icon placeholder
  arrowLeft = "$arrowLeft",
  arrowRight = "$arrowRight",
  circle = "$circle",
  triangle = "$triangle",
  square = "$square",
  pentagon = "$pentagon",
  hexagon = "$hexagon",
  circleOutline = "$circleOutline",
  triangleOutline = "$triangleOutline",
  squareOutline = "$squareOutline",
  pentagonOutline = "$pentagonOutline",
  hexagonOutline = "$hexagonOutline",
  rewindOutline = "$rewindOutline",
  fastForwardOutline = "$fastForwardOutline",
  playOutline = "$playOutline",
  skipPreviousOutline = "$skipPreviousOutline",
  skipNextOutline = "$skipNextOutline",

  bus = "$bus",
  train = "$train",
  car = "$car",
  taxi = "$taxi",
  fileGifBox = "$fileGifBox",

  magnify = "$magnify",
  checkboxMarked = "$checkboxMarked",
  minusBox = "$minusBox",
  checkboxOutline = "$checkboxOutline",
  checkboxBlankOutline = "$checkboxBlankOutline",
  minusBoxOutline = "$minusBoxOutline",
  emailOutline = "$emailOutline",
  bookmark = "$bookmark",
  bookmarkOutline = "$bookmarkOutline",
  accountOutline = "$accountOutline",
  message = "$message",
  messageOutline = "$messageOutline",
  trashCanOutline = "$trashCanOutline",
  folderOutline = "$folderOutline",
  menuDown = "$menuDown",
  menuUp = "$menuUp",
  menuLeft = "$menuLeft",
  menuRight = "$menuRight",
  paperclip = "$paperclip",
  calendarToday = "$calendarToday",
  shareVariantOutline = "$shareVariantOutline",
  keyboardOutline = "$keyboardOutline",
  cogOutline = "$cogOutline",
  cog = "$cog",
  clockOutline = "$clockOutline",
  keyboardReturn = "$keyboardReturn",
  stickerEmoji = "$stickerEmoji",
  dotsHorizontal = "$dotsHorizontal",
  microphone = "$microphone",
  web = "$web",
  googleTranslate = "$googleTranslate",
  imageOutline = "$imageOutline",
  trayArrowUp = "$trayArrowUp",
  trayArrowDown = "$trayArrowDown",

  // ToolBar
  weatherSunny = "$weatherSunny",
  weatherNight = "$weatherNight",
  accountCircle = "$accountCircle",

  // Table
  checkCircleOutline = "$checkCircleOutline",
  dotsVertical = "$dotsVertical",
  arrowUp = "$arrowUp",
  arrowDown = "$arrowDown",
  filterVariant = "$filterVariant",

  // SignIn
  microsoftAzure = "$microsoftAzure",

  // Sections
  home = "$home",
  security = "$security",

  // Navigation icons
  schema = "$schema",
  group = "$group",
  hotel = "$hotel",
  globe = "$globe",
  signLanguage = "$signLanguage",
  map = "$map",
  pinDrop = "$pinDrop",
  restaurant = "$restaurant",
  preview = "$preview",
  table = "$table",
  gridView = "$gridView",
  assignmentInd = "$assignmentInd",
  handshake = "$handshake",
  videoGames = "$videoGames",
  videoGamesRetro = "$videoGamesRetro",
  manageAccounts = "$manageAccounts",
  personAdd = "$personAdd",
  flag = "$flag",

  checkSmall = "$checkSmall",
  mobileFirendly = "$mobileFriendly",

  calendar = "$calendarMonth",

  language = "$language",
  help = "$help",

  favorite = "$favorite",
  pallete = "$palette",
  database = "$database",
  archive = "$archive",
  beachAccess = "$beachAccess",
  wc = "$wc",
  bed = "$bed",
  roomService = "$roomService",
  vpnKey = "$vpnKey",

  // SignIn
  login = "$login",
  logout = "$logout",
}
