import type { IconAliases } from "vuetify";
import {
  // Defaults: In Use
  mdiChevronLeft,
  mdiChevronRight,
  mdiCheck,
  mdiMinus,
  mdiChevronUp,
  mdiChevronDown,
  mdiPencil,
  mdiCancel,
  mdiAlertCircle,
  mdiClose,
  mdiDelete,
  mdiCloseCircleOutline,
  mdiCheckCircleOutline,
  mdiInformationOutline,
  mdiAlertOctagonOutline,
  mdiCheckboxOutline,
  mdiCheckboxBlankOutline,
  mdiMinusBoxOutline,
  mdiSortDescending,
  mdiSortAscending,
  mdiSort,
  mdiMenu,
  mdiSubdirectoryArrowRight,
  mdiRadioboxMarked,
  mdiRadioboxBlank,
  mdiStarOutline,
  mdiStar,
  mdiStarHalfFull,
  mdiLoading,
  mdiPageFirst,
  mdiPageLast,
  mdiUnfoldMoreHorizontal,
  mdiFile,
  mdiPlus,

  // Mediakiwi: Defaults (some might already be included in the above list)
  mdiArrowLeft,
  mdiArrowRight,
  mdiCircle,
  mdiTriangle,
  mdiSquare,
  mdiPentagon,
  mdiHexagon,
  mdiCircleOutline,
  mdiTriangleOutline,
  mdiSquareOutline,
  mdiPentagonOutline,
  mdiHexagonOutline,
  mdiRewindOutline,
  mdiFastForwardOutline,
  mdiPlayOutline,
  mdiSkipPreviousOutline,
  mdiSkipNextOutline,
  //outline not available
  mdiBus,
  mdiTrain,
  mdiCar,
  mdiTaxi,
  mdiFileGifBox,
  // checkSmall?
  // mobileFirendly?
  mdiMagnify,
  mdiCheckboxMarked,
  mdiMinusBox,
  mdiEmailOutline,
  mdiBookmark,
  mdiBookmarkOutline,
  mdiAccountOutline,
  mdiMessage,
  mdiMessageOutline,
  mdiTrashCanOutline,
  mdiFolderOutline,
  mdiMenuDown,
  mdiMenuUp,
  mdiMenuLeft,
  mdiMenuRight,
  mdiPaperclip,
  mdiCalendarToday,
  mdiCalendar,
  mdiShareVariantOutline,
  mdiKeyboardOutline,
  mdiCogOutline,
  mdiCog,
  mdiClockOutline,
  mdiKeyboardReturn,
  mdiStickerEmoji,
  mdiDotsHorizontal,
  mdiMicrophone,
  mdiWeb,
  mdiGoogleTranslate,
  mdiImageOutline,
  mdiTrayArrowUp,
  mdiTrayArrowDown,

  // ToolBar
  mdiWeatherSunny,
  mdiWeatherNight,
  mdiAccountCircle,

  // Table
  mdiDotsVertical,
  mdiArrowUp,
  mdiArrowDown,
  mdiFilterVariant,

  // SignIn
  mdiMicrosoftAzure,

  // Sections
  mdiHome,
  mdiSecurity,
} from "@mdi/js";

/** aliases that directly correlates to the icons available for use in mediakiwi
 * [LA]: last updated: 01-08-2023
 * please refer to the confluence and figma page for the latest list of icons
 */
export const mediakiwiIconAliases: IconAliases = {
  // default icon aliases (from vuetify)
  collapse: mdiChevronUp,
  complete: mdiCheck,
  cancel: mdiCancel,
  close: mdiClose,
  delete: mdiDelete,
  clear: mdiCloseCircleOutline,
  success: mdiCheckCircleOutline,
  info: mdiInformationOutline,
  warning: mdiAlertOctagonOutline,
  error: mdiAlertCircle,
  prev: mdiChevronLeft,
  next: mdiChevronRight,
  checkboxOn: mdiCheckboxOutline,
  checkboxOff: mdiCheckboxBlankOutline,
  checkboxIndeterminate: mdiMinusBoxOutline,
  delimiter: mdiDotsVertical,
  sort: mdiSort,
  expand: mdiChevronDown,
  menu: mdiMenu,
  subgroup: mdiSubdirectoryArrowRight,
  dropdown: mdiChevronDown,
  radioOn: mdiRadioboxMarked,
  radioOff: mdiRadioboxBlank,
  edit: mdiPencil,
  ratingEmpty: mdiStarOutline,
  ratingFull: mdiStar,
  ratingHalf: mdiStarHalfFull,
  loading: mdiLoading,
  first: mdiPageFirst,
  last: mdiPageLast,
  unfold: mdiUnfoldMoreHorizontal,
  closeCircleOutline: mdiCloseCircleOutline,
  file: mdiFile,
  plus: mdiPlus,
  minus: mdiMinus,
  sortDesc: mdiSortDescending,
  sortAsc: mdiSortAscending,
  chevronLeft: mdiChevronLeft,
  chevronRight: mdiChevronRight,
  informationOutline: mdiInformationOutline,

  // Mediakiwi: Defaults (some might already be included in the above list)
  unknown: mdiCheckboxBlankOutline, // used for blank icon placeholder
  arrowLeft: mdiArrowLeft,
  arrowRight: mdiArrowRight,
  circle: mdiCircle,
  triangle: mdiTriangle,
  square: mdiSquare,
  pentagon: mdiPentagon,
  hexagon: mdiHexagon,
  circleOutline: mdiCircleOutline,
  triangleOutline: mdiTriangleOutline,
  squareOutline: mdiSquareOutline,
  pentagonOutline: mdiPentagonOutline,
  hexagonOutline: mdiHexagonOutline,
  rewindOutline: mdiRewindOutline,
  fastForwardOutline: mdiFastForwardOutline,
  playOutline: mdiPlayOutline,
  skipPreviousOutline: mdiSkipPreviousOutline,
  skipNextOutline: mdiSkipNextOutline,
  // Some outline icons are part of material design outline and not icons
  bus: mdiBus, // bus outline is part of material symbols andn not icons
  trian: mdiTrain, // train outline is part of material symbols andn not icons
  car: mdiCar, // car outline is part of material symbols andn not icons
  taxi: mdiTaxi, // taxi outline is part of material symbols andn not icons
  fileGifBox: mdiFileGifBox,
  // checkSmall is part of material symbols andn not icons
  // mobileFirendly is part of material symbols andn not icons
  magnify: mdiMagnify,
  checkboxMarked: mdiCheckboxMarked,
  minusBox: mdiMinusBox,
  checkboxOutline: mdiCheckboxOutline,
  checkboxBlankOutline: mdiCheckboxBlankOutline,
  minusBoxOutline: mdiMinusBoxOutline,
  emailOutline: mdiEmailOutline,
  bookmark: mdiBookmark,
  bookmarkOutline: mdiBookmarkOutline,
  accountOutline: mdiAccountOutline,
  message: mdiMessage,
  messageOutline: mdiMessageOutline,
  trashCanOutline: mdiTrashCanOutline,
  folderOutline: mdiFolderOutline,
  menuDown: mdiMenuDown,
  menuUp: mdiMenuUp,
  menuLeft: mdiMenuLeft,
  menuRight: mdiMenuRight,
  paperclip: mdiPaperclip,
  calendarToday: mdiCalendarToday,
  calendar: mdiCalendar,
  shareVariantOutline: mdiShareVariantOutline,
  keyboardOutline: mdiKeyboardOutline,
  cogOutline: mdiCogOutline,
  cog: mdiCog,
  clockOutline: mdiClockOutline,
  keyboardReturn: mdiKeyboardReturn,
  stickerEmoji: mdiStickerEmoji,
  dotsHorizontal: mdiDotsHorizontal,
  microphone: mdiMicrophone,
  web: mdiWeb,
  googleTranslate: mdiGoogleTranslate,
  imageOutline: mdiImageOutline,
  trayArrowUp: mdiTrayArrowUp,
  trayArrowDown: mdiTrayArrowDown,

  // ToolBar
  weatherSunny: mdiWeatherSunny,
  weatherNight: mdiWeatherNight,
  accountCircle: mdiAccountCircle,

  // Table
  checkCircleOutline: mdiCheckCircleOutline,
  dotsVertical: mdiDotsVertical,
  arrowUp: mdiArrowUp,
  arrowDown: mdiArrowDown,
  filterVariant: mdiFilterVariant,

  // SignIn
  microsoftAzure: mdiMicrosoftAzure,

  // Sections
  home: mdiHome,
  security: mdiSecurity,
};
