import {
  // Standard: In Use
  mdiChevronLeft,
  mdiChevronRight,
  mdiPuzzle,

  // Sections
  mdiHome,
  mdiSecurity,

  // ToolBar
  mdiWeatherSunny,
  mdiWeatherNight,
  mdiAccountCircle,

  // Table
  mdiCheckCircleOutline,
  mdiDotsVertical,
  mdiCloseCircleOutline,
  mdiArrowUp,
  mdiArrowDown,
  mdiFilterVariant,
  mdiClose,
  mdiPlus,

  // SignIn
  mdiMicrosoftAzure,

  // Alerts
  mdiInformationOutline,

  // Standard: NOT In Use
  mdiMinus,
  mdiChevronUp,
  mdiChevronDown,
  mdiPin,
  mdiMapMarkerRadius,
  mdiMapSearch,
  mdiMagnify,
  mdiMagnifyPlus,
  mdiMagnifyMinus,
  mdiUpload,
  mdiDownload,
  mdiAccountGroup,
  mdiFolder,
  mdiAirplaneLanding,
  mdiAirplaneTakeoff,
  mdiSend,
  mdiInbox,
  mdiInboxArrowUp,
  mdiBus,
  mdiCar,
  mdiCogOutline,
  mdiClock,
  mdiMap,
  mdiSlashForward,
  mdiFinance,
  mdiViewDashboard,
  mdiCashMultiple,
  mdiBitcoin,
  mdiBookmark,
  mdiStar,
  mdiBook,
  mdiArchive,
  mdiBug,
  mdiFormatListBulletedSquare,
  mdiPencil,
  mdiChat,
  mdiLoginVariant,
  mdiLogoutVariant,
  mdiPhone,
  mdiAlertOutline,
  mdiAlert,
  mdiInformation,
  mdiHelp,
  mdiCloudOutline,
  mdiFileDocumentOutline,
  mdiBed,
  mdiUmbrella,
  mdiWaves,
  mdiWater,
  mdiTimerSand,
  mdiWeb,
  mdiEarth,
  mdiWeatherSnowy,
  mdiWeatherPouring,
  mdiWeatherWindy,
  mdiWeatherSunset,
  mdiClockOutline,
  mdiCalendarMonth,
  mdiCalendarBlank,
  mdiUpdate,
  mdiLockOutline,
  mdiLockOpenOutline,
  mdiEyeOutline,
  mdiEyeOffOutline,
  mdiHeart,
  mdiVolumeOff,
  mdiVolumeHigh,
  mdiBlockHelper,
  mdiFlagVariant,
  mdiSale,
  mdiCookieOutline,
  mdiLeaf,
  mdiAlertOctagon,
  mdiMonitor,
  mdiTools,
  mdiBankOutline,
  mdiEmoticonHappyOutline,
  mdiEmoticonSadOutline,
  mdiEmoticonSickOutline,
  mdiRobotConfusedOutline,
  mdiRobotHappy,
  mdiTranslate,
  mdiHandshakeOutline,
  mdiDumbbell,
  mdiEmail,
  mdiAt,
  mdiTrashCanOutline,
  mdiCloseOctagon,
  mdiOpenInNew,

  // SampleWeb
  // TODO: these need to be ported to sample web
  mdiForward,
  mdiAccountCheck,
  mdiAlertCircle,

  // custom icons
  mdiCheck,
  mdiCancel,
  mdiSortDescending,
  mdiSortAscending,
  mdiDelete,
  mdiAlertOctagonOutline,
  mdiCheckboxBlankOutline,
  mdiCheckboxOutline,
  mdiMinusBoxOutline,
  mdiSort,
  mdiMenu,
  mdiSubdirectoryArrowRight,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiStarOutline,
  mdiStarHalfFull,
  mdiLoading,
  mdiPageFirst,
  mdiPageLast,
  mdiUnfoldMoreHorizontal,
  mdiFile,
} from "@mdi/js";

// custom Icon iconset from mdi svgs
// add more here if needed
export const mediakiwiIconAliases = {
  // default icon aliases
  collapse: mdiChevronUp,
  complete: mdiCheck,
  cancel: mdiCancel,
  close: mdiClose,
  delete: mdiDelete,
  clear: mdiCloseCircleOutline,
  success: mdiCheckCircleOutline,
  info: mdiInformationOutline,
  warning: mdiAlertOctagonOutline,
  error: mdiAlertCircle,
  prev: mdiChevronLeft,
  next: mdiChevronRight,
  checkboxOn: mdiCheckboxOutline,
  checkboxOff: mdiCheckboxBlankOutline,
  checkboxIndeterminate: mdiMinusBoxOutline,
  delimiter: mdiDotsVertical,
  sort: mdiSort,
  expand: mdiChevronDown,
  menu: mdiMenu,
  subgroup: mdiSubdirectoryArrowRight,
  dropdown: mdiChevronDown,
  radioOn: mdiRadioboxMarked,
  radioOff: mdiRadioboxBlank,
  edit: mdiPencil,
  ratingEmpty: mdiStarOutline,
  ratingFull: mdiStar,
  ratingHalf: mdiStarHalfFull,
  loading: mdiLoading,
  first: mdiPageFirst,
  last: mdiPageLast,
  unfold: mdiUnfoldMoreHorizontal,
  file: mdiFile,
  plus: mdiPlus,
  minus: mdiMinus,
  sortDesc: mdiSortDescending,
  sortAsc: mdiSortAscending,

  // Standard: In Use
  chevronLeft: mdiChevronLeft,
  chevronRight: mdiChevronRight,
  puzzle: mdiPuzzle,

  // Sections
  home: mdiHome,
  security: mdiSecurity,

  // ToolBar
  weatherSunny: mdiWeatherSunny,
  weatherNight: mdiWeatherNight,
  accountCircle: mdiAccountCircle,

  // Table
  checkCircleOutline: mdiCheckCircleOutline,
  dotsVertical: mdiDotsVertical,
  closeCircleOutline: mdiCloseCircleOutline,
  arrowUp: mdiArrowUp,
  arrowDown: mdiArrowDown,
  filterVariant: mdiFilterVariant,

  // SignIn
  microsoftAzure: mdiMicrosoftAzure,

  // Alerts
  informationOutline: mdiInformationOutline,

  // Standard: NOT In Use
  chevronUp: mdiChevronUp,
  chevronDown: mdiChevronDown,
  pin: mdiPin,
  mapMarkerRadius: mdiMapMarkerRadius,
  mapSearch: mdiMapSearch,
  magnify: mdiMagnify,
  magnifyPlus: mdiMagnifyPlus,
  magnifyMinus: mdiMagnifyMinus,
  upload: mdiUpload,
  download: mdiDownload,
  accountGroup: mdiAccountGroup,
  folder: mdiFolder,
  airplaneLanding: mdiAirplaneLanding,
  airplaneTakeOff: mdiAirplaneTakeoff,
  send: mdiSend,
  inbox: mdiInbox,
  inboxArrrowUp: mdiInboxArrowUp,
  bus: mdiBus,
  car: mdiCar,
  cogOutline: mdiCogOutline,
  clock: mdiClock,
  map: mdiMap,
  slashForward: mdiSlashForward,
  finance: mdiFinance,
  viewDashboard: mdiViewDashboard,
  cashMultiple: mdiCashMultiple,
  bitcoin: mdiBitcoin,
  bookmark: mdiBookmark,
  star: mdiStar,
  book: mdiBook,
  archive: mdiArchive,
  bug: mdiBug,
  formatListBulletedSquare: mdiFormatListBulletedSquare,
  pencil: mdiPencil,
  chat: mdiChat,
  loginVariant: mdiLoginVariant,
  logoutVariant: mdiLogoutVariant,
  phone: mdiPhone,
  alertOutline: mdiAlertOutline,
  alert: mdiAlert,
  information: mdiInformation,
  help: mdiHelp,
  cloudOutline: mdiCloudOutline,
  fileDocumentOutline: mdiFileDocumentOutline,
  bed: mdiBed,
  umbrella: mdiUmbrella,
  waves: mdiWaves,
  water: mdiWater,
  timerSand: mdiTimerSand,
  web: mdiWeb,
  earth: mdiEarth,
  weatherSnowy: mdiWeatherSnowy,
  weatherPouring: mdiWeatherPouring,
  weatherWindy: mdiWeatherWindy,
  weatherSunset: mdiWeatherSunset,
  clockOutline: mdiClockOutline,
  calendarMonth: mdiCalendarMonth,
  calendarBlank: mdiCalendarBlank,
  update: mdiUpdate,
  lockOutline: mdiLockOutline,
  lockOpenOutline: mdiLockOpenOutline,
  eyeOutline: mdiEyeOutline,
  eyeOffOutline: mdiEyeOffOutline,
  heart: mdiHeart,
  volumeOff: mdiVolumeOff,
  volumeHigh: mdiVolumeHigh,
  blockHelper: mdiBlockHelper,
  flagVariant: mdiFlagVariant,
  sale: mdiSale,
  cookiesOutline: mdiCookieOutline,
  leaf: mdiLeaf,
  alertOctagon: mdiAlertOctagon,
  monitor: mdiMonitor,
  tools: mdiTools,
  bankOutline: mdiBankOutline,
  emoticonHappyOutline: mdiEmoticonHappyOutline,
  emoticonSadOutline: mdiEmoticonSadOutline,
  emoticonSickOutline: mdiEmoticonSickOutline,
  emoticonConfusedOutline: mdiRobotConfusedOutline,
  robotHappy: mdiRobotHappy,
  translate: mdiTranslate,
  handshakeOutline: mdiHandshakeOutline,
  dumbbell: mdiDumbbell,
  email: mdiEmail,
  at: mdiAt,
  trashCanOutline: mdiTrashCanOutline,
  closeOctagon: mdiCloseOctagon,
  openInNew: mdiOpenInNew,

  // SampleWeb
  // TODO: these need to be ported to sample web
  accountCheck: mdiAccountCheck,
  alertCircle: mdiAlertCircle,
  forward: mdiForward,
};
