name: DEV / TEST - Deploy sampleweb portal app to Azure Static Web Apps

env:
  APP_LOCATION: "/src/Sushi.MediaKiwi.Vue/" # location of your client code
  OUTPUT_LOCATION: "sampleweb" # location of client code build output

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  # Deploy to DEV environment
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    env:
      VITE_APP_MEDIAKIWI_APIBASEURL: https://mediakiwi-sample-api-dev.azurewebsites.net/mediakiwi/api
      VITE_APP_MEDIAKIWI_MSALCONFIG_AUTH_CLIENTID: 7cd2eddb-b79e-4e04-ac24-0011821ccb8e
      VITE_APP_MEDIAKIWI_MSALCONFIG_AUTH_AUTHORITY: https://login.microsoftonline.com/95c90a04-5ea8-465e-ac3e-1aae3b29b0c9
      VITE_APP_MEDIAKIWI_MSALCONFIG_AUTH_REDIRECTURI: /loginRedirect
      VITE_APP_MEDIAKIWI_MSALCONFIG_AUTH_POSTLOGOUTREDIRECTURI: /signIn
      VITE_APP_SAMPLEAPI_APIBASEURL: https://mediakiwi-sample-api-dev.azurewebsites.net/
    name: Dev - Build and Deploy Portal
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Build code and deploy to DEV
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEV_AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          skip_api_build: "true"
          app_build_command: "npm run build:sample"
