# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Publish - MediaKiwi.Vue

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Update package.json version
        run: |
          cd src/Sushi.MediaKiwi.Vue
          NEW_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/v//')
          jq '.version = $new_version' --arg new_version "${NEW_VERSION}" package.json > package.json.tmp && mv package.json.tmp package.json
          cd ../..

      - name: Build package
        run: |
          cd src/Sushi.MediaKiwi.Vue
          npm run build

      - name: Authenticate with NPM registry
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package to NPM
        run: npm publish --access public
