name: NuGet Publish - Sushi.MediaKiwi

on:
  release:
    types: [created]

jobs:
  publish-mediakiwi:
    name: 'Publish Mediakiwi NuGet Package'
    runs-on: ubuntu-latest

    steps:
      
      # Set VERSION variable from Release Tag
      - name: Set VERSION variable from Release Tag
        run: echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      # Checkout Main branch
      - name: 'Checkout Main'
        uses: actions/checkout@v4
        with:
          ref: main
          
      # Setup .NET
      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      # Create NuGet Package
      - name: 'Create NuGet Package'
        working-directory: src/Sushi.MediaKiwi.Core
        run: dotnet pack --configuration Release /p:Version=${VERSION} --output .
      
      # Push NuGet Package
      - name: Push to NuGet
        working-directory: src/Sushi.MediaKiwi.Core
        run: dotnet nuget push Sushi.MediaKiwi.Core.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.MEDIAKIWI_NUGET_2023 }}
