name: dotnet

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/pr_dotnet.yml"
      - "src/Sushi.MediaKiwi.AzureFunction/**/*"
      - "src/Sushi.MediaKiwi.DAL/**/*"
      - "src/Sushi.MediaKiwi.SampleAPI/**/*"
      - "src/Sushi.MediaKiwi.Services/**/*"
      - "src/Sushi.MediaKiwi.WebAPI/**/*"
      - "tests/**/*"

# Add "id-token" with the intended permissions.
permissions:
  contents: "read"
  id-token: "write"
  # Required to put a comment into the pull-request
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server
        env:
          SA_PASSWORD: Your_password123
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
    steps:

      # Checkout current branch
      - name: Checkout
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build
        run: dotnet build --no-restore

      # Run tests
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage

      - name: Merge Coverage Reports
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate Merged Coverage Report
        run: reportgenerator "-reports:coverage/**/coverage.cobertura.xml" "-targetdir:mergedcoveragereport" "-reporttypes:Html;Cobertura"

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "mergedcoveragereport/Cobertura.xml"
          badge: true
          format: "markdown"
          output: "both"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
