name: vite

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "src/Sushi.MediaKiwi.Vue/**/*"

# Add "id-token" with the intended permissions.
permissions:
  contents: "read"
  id-token: "write"
  # Required to put a comment into the pull-request
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./src/Sushi.MediaKiwi.Vue

      - name: Run Vite Test
        run: npm run vi:coverage
        working-directory: ./src/Sushi.MediaKiwi.Vue

      - name: "Report Coverage"
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./src/Sushi.MediaKiwi.Vue
          json-summary-path: ${working-directory}/test/unit/coverage/coverage-summary.json
          json-final-path: ${working-directory}/test/unit/coverage/coverage-final.json

      - name: Run Vite Build
        run: npm run build
        working-directory: ./src/Sushi.MediaKiwi.Vue
